// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLsGkhqdGXA29DAHPu3in2TjC_mn0rFy8',
    appId: '1:878015482310:web:7ab14e668a642e244b8ac7',
    messagingSenderId: '878015482310',
    projectId: 'simara-app-28443',
    authDomain: 'simara-app-28443.firebaseapp.com',
    storageBucket: 'simara-app-28443.firebasestorage.app',
    measurementId: 'G-5441WMN2XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUYgwUzQiv4m14eXfZnzviXKABbOUywNw',
    appId: '1:878015482310:android:a02236e5d5fa20d14b8ac7',
    messagingSenderId: '878015482310',
    projectId: 'simara-app-28443',
    storageBucket: 'simara-app-28443.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1CgAhm1qGKDtHOTRDlHITGss6WgkEhCo',
    appId: '1:878015482310:ios:df0da121497102004b8ac7',
    messagingSenderId: '878015482310',
    projectId: 'simara-app-28443',
    storageBucket: 'simara-app-28443.firebasestorage.app',
    iosClientId: '878015482310-ahtqs8l51g9uogl64hvcbq8jvvlm6dvh.apps.googleusercontent.com',
    iosBundleId: 'com.simara.simara',
  );
}
